name: Test Action

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          env: |
            NODE_ENV=test
            PROCESS_ONE=test2
            SOME_RANDOM_VAR=test3
            ANOTHER_ONE=test4

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.envpath }}"
